
spring:
#  resources:
#    static-locations: classpath:static/
  datasource:
    username: root
    password: 11111111
    url: jdbc:mysql://127.0.0.1:3306/bandao?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  mvc:
    servlet:
      path: /health
  redis:
    host: 127.0.0.1
    database: 0

  data:
    redis:
      repositories:
        enabled: false
    elasticsearch:
      repositories:
        enabled: false


cloud:
  tencent:
    secretId: ${TENCENT_SECRET_ID:secretId}
    secretKey: ${TENCENT_SECRET_KEY:secretKey}
  baidu:
    secretId: ${BAIDU_SECRET_ID:secretId}
    secretKey: ${BAIDU_SECRET_KEY:secretKey}
  kdxf:
    appId: ${KDXF_APP_ID:appId}
    appKey: ${KDXF_APP_KEY:appKey}
    ocrUrl: https://webapi.xfyun.cn/v1/service/v1/ocr/general

wx:
  key: ${WX_KEY:xx}
  privateKey: ${WX_PRIVATE_KEY:XX}
  mchId: ${WX_MCH_ID:xx}
  mchSerialNo: ${WX_MCH_SERIAL_NO:xx}
  apiV3Key: ${WX_API_V3_KEY:xx}
  appid: ${WX_APP_ID:xx}
  appSecret: ${WX_APP_SECRET:xx}